import {context,trace,SpanStatusCode} from '@opentelemetry/api';
import type {ObservationStore} from './store.js'; import type {Attributes,EventRecord,LogRecord,MetricRecord,SpanRecord,TelemetryRecord} from './types.js'; import type {ObservabilityExporter} from './exporter.js'; import {redactAttributes} from './redaction.js';
const nowNano=()=>BigInt(Date.now())*1000000n;
export class FullObservabilityRuntime { constructor(private readonly options:{store:ObservationStore;exporters?:ObservabilityExporter[]}){} private async fanout(record:TelemetryRecord){const safe={...record,attributes:redactAttributes(record.attributes)} as TelemetryRecord;try{if(safe.signal==='span')await this.options.store.writeSpan(safe);else if(safe.signal==='log')await this.options.store.writeLog(safe);else if(safe.signal==='metric')await this.options.store.writeMetric(safe);else await this.options.store.writeEvent(safe)}catch{} for(const e of this.options.exporters??[]){try{await e.export([safe])}catch{}}}
async log(body:unknown,attributes:Attributes={},severityText='INFO'){const a=trace.getSpan(context.active())?.spanContext();const r:LogRecord={signal:'log',timestampUnixNano:nowNano(),body,severityText,attributes,traceId:a?.traceId,spanId:a?.spanId};await this.fanout(r)}
async metric(name:string,value:number,attributes:Attributes={}){const r:MetricRecord={signal:'metric',name,value,kind:'gauge',timestampUnixNano:nowNano(),attributes};await this.fanout(r)}
async event(name:string,body?:unknown,attributes:Attributes={}){const a=trace.getSpan(context.active())?.spanContext();const r:EventRecord={signal:'event',name,body,timestampUnixNano:nowNano(),attributes,traceId:a?.traceId,spanId:a?.spanId};await this.fanout(r)}
async observe<T>(name:string,fn:()=>Promise<T>,attributes:Attributes={}):Promise<T>{const tracer=trace.getTracer('@allascode/full-observability');const started=nowNano();return tracer.startActiveSpan(name,async span=>{let status:SpanRecord['status']='ok';try{const result=await fn();span.setStatus({code:SpanStatusCode.OK});return result}catch(error){status='error';span.setStatus({code:SpanStatusCode.ERROR});throw error}finally{const ctx=span.spanContext();span.end();await this.fanout({signal:'span',traceId:ctx.traceId,spanId:ctx.spanId,name,kind:'internal',startTimeUnixNano:started,endTimeUnixNano:nowNano(),status,attributes})}})}
async flush(){await this.options.store.flush();for(const e of this.options.exporters??[]){try{await e.forceFlush()}catch{}}} async shutdown(){await this.flush();await this.options.store.shutdown();for(const e of this.options.exporters??[]){try{await e.shutdown()}catch{}}}
}
